### ISSUE TITLE
Latest version missing from mavenCentral

### ISSUE THREAD

**Issue by RootingInLoad** [toxicity188/BetterModel#3]
Hi ! BetterModel is only available up to 1.2 on mavenCentral: https://repo.maven.apache.org/maven2/io/github/toxicity188/BetterModel/

Though, the latest version is 1.3 on GitHub.

Is this expected behavior ?

**Comment by toxicity188** [comment]
Not intended;
I have to make javadoc but need more time :(

**Comment by RootingInLoad** [comment]
> Not intended; I have to make javadoc but need more time :(

No problem, no pressure of course !

Thanks !
